import Head from "next/head";
import dynamic from "next/dynamic";

const Experience = dynamic(() => import("../component/Experience"));
const Proyectos = dynamic(() => import("../component/Proyectos"));
const Download = dynamic(() => import("../component/Download"));

export default function Home() {
  return (
    <>
      <Head>
        <title>CV</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Experience />
      <Proyectos />
      <Download />
    </>
  );
}
