import Head from "next/head";
import AboutMe from "../component/AboutMe";
import Experience from "../component/Experience";
import Profile from "../component/Profile";
import Proyectos from "../component/Proyectos";
import Footer from "../component/Footer";
import Download from "../component/Download";

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Profile />
      <AboutMe />
      <Experience />
      <Proyectos />
      <Download />
      <Footer />
    </>
  );
}
